# Generated by Django 4.1.7 on 2023-02-18 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=50)),
                ('number', models.IntegerField(default='')),
                ('engine', models.CharField(choices=[('diesla', 'diesla'), ('gas', 'gas'), ('petrol', 'petrol')], default='', max_length=10)),
                ('year', models.PositiveSmallIntegerField(help_text='production date')),
                ('description', models.TextField(blank=True, max_length=512)),
                ('image', models.ImageField(blank=True, upload_to='cars/')),
                ('is_available', models.BooleanField(default=True)),
                ('capacity', models.CharField(default='', max_length=2)),
                ('rent', models.CharField(default='', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='standard', max_length=24, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.CharField(max_length=32)),
                ('end_date', models.CharField(max_length=32)),
                ('brand', models.ForeignKey(default='', max_length=32, on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('user', models.ForeignKey(max_length=32, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.category'),
        ),
    ]
